# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vrfy_Cmd',
            fields=[
                ('VRFY_CMD_NO', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='검증명령어번호')),
                ('VRFY_SEQ', models.IntegerField(verbose_name='검증순번')),
                ('AUTO_CK_YN', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='자동체크여부')),
                ('CMD_DVS_CD', models.CharField(choices=[('VRFY', '검증'), ('EXE', '실행')], default='VRFY', max_length=20, verbose_name='명령어구분코드')),
                ('CMD_TYPE_CD', models.CharField(choices=[('AURORA_SQL', 'AURORA_SQL'), ('SHELL', 'Shell'), ('AURORA_PROC', 'AURORA프로시져'), ('ATHENA_SQL', 'ATHENA_SQL')], default='AURORA_SQL', max_length=20, verbose_name='명령어유형코드')),
                ('CMD_CNTS', models.TextField(blank=True, default=None, max_length=4000, null=True, verbose_name='명령어내용')),
                ('DTL_VRFY_YN', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='상세검증여부')),
                ('LAST_EXE_DTTM', models.DateTimeField(default=datetime.datetime(2018, 3, 30, 15, 48, 11, 431988), verbose_name='마지막수행일시')),
                ('RGSTR_ID', models.CharField(default='DA', max_length=30, verbose_name='등록자ID')),
                ('RGST_DTTM', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('MODR_ID', models.CharField(default='DA', max_length=30, verbose_name='수정자ID')),
                ('MODI_DTTM', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('VRFY_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dq.Vrfy')),
            ],
        ),
        migrations.RemoveField(
            model_name='vrfycmd',
            name='VRFY_NO',
        ),
        migrations.DeleteModel(
            name='VrfyCmd',
        ),
    ]
