# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 08:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrfy',
            name='CMD_CNTS',
            field=models.TextField(blank=True, default=None, max_length=14000, null=True, verbose_name='검증내용'),
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 17, 1, 40, 325064), verbose_name='마지막수행일시'),
        ),
    ]
