# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0002_auto_20180713_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrfy',
            name='REFRC_TABLE_HANGL_NM',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='참조테이블한글명'),
        ),
        migrations.AlterField(
            model_name='vrfy',
            name='REFRC_TABLE_NM',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='참조테이블명'),
        ),
        migrations.AlterField(
            model_name='vrfy',
            name='VRFY_EXPLN',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='검증설명'),
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 17, 10, 43, 296120), verbose_name='마지막수행일시'),
        ),
    ]
