# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 04:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0002_auto_20180330_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 13, 20, 53, 953307), verbose_name='마지막수행일시'),
        ),
    ]
