# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 08:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0003_auto_20180713_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrfy',
            name='CMD_TYPE_CD',
            field=models.CharField(choices=[('01', 'AURORA_SQL'), ('02', 'ATHENA_SQL'), ('03', 'DynameDB_QRY'), ('04', 'RED_SHIFT_QRY'), ('05', 'SHELL'), ('99', '기타')], default='01', max_length=30, verbose_name='명령유형코드'),
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 17, 14, 50, 606266), verbose_name='마지막수행일시'),
        ),
    ]
