# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0005_auto_20180716_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrfyLog',
            fields=[
                ('VRFY_LOG_NO', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='검증로그번호')),
                ('VRFY_NM', models.CharField(max_length=100, verbose_name='검증명')),
                ('CMD_TYPE_CD', models.CharField(choices=[('AURORA_SQL', 'AURORA_SQL'), ('ATHENA_SQL', 'ATHENA_SQL'), ('DYNAMODB_QRY', 'DYNAMODB_QRY'), ('REDSHIFT_SQL', 'REDSHIFT_SQL'), ('SHELL', 'SHELL'), ('ETC', 'ETC')], default='01', max_length=30, verbose_name='명령유형코드')),
                ('CMD_CNTS', models.TextField(blank=True, default=None, max_length=14000, null=True, verbose_name='검증내용')),
                ('RGSTR_ID', models.CharField(default='DA', max_length=30, verbose_name='등록자ID')),
                ('RGST_DTTM', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('MODR_ID', models.CharField(default='DA', max_length=30, verbose_name='수정자ID')),
                ('MODI_DTTM', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
        ),
        migrations.AlterField(
            model_name='vrfy',
            name='CMD_TYPE_CD',
            field=models.CharField(choices=[('AURORA_SQL', 'AURORA_SQL'), ('ATHENA_SQL', 'ATHENA_SQL'), ('DYNAMODB_QRY', 'DYNAMODB_QRY'), ('REDSHIFT_SQL', 'REDSHIFT_SQL'), ('SHELL', 'SHELL'), ('ETC', 'ETC')], default='01', max_length=30, verbose_name='명령유형코드'),
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 11, 29, 35, 27709), verbose_name='마지막수행일시'),
        ),
        migrations.AddField(
            model_name='vrfylog',
            name='VRFY_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dq.Vrfy'),
        ),
    ]
