# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0006_auto_20180718_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrfylog',
            name='VRFY_RSLT_VAL',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='검증결과값'),
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 16, 0, 26, 654562), verbose_name='마지막수행일시'),
        ),
    ]
