# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0008_auto_20180719_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dlcm',
            fields=[
                ('DLCM_NO', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='DLC관리번호')),
                ('DB_NM', models.CharField(max_length=100, verbose_name='DB명')),
                ('SCHEMA_NM', models.CharField(max_length=100, verbose_name='스키마명')),
                ('CLSF_NM1', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='대분류명')),
                ('CLSF_NM2', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='중분류명')),
                ('DLCM_TYPE_DTL_CD', models.CharField(choices=[('DEL', '데이터삭제'), ('ARC', '아카이빙'), ('COPY', '복제'), ('ETC', '키타')], default='BIZ_RUL', max_length=30, verbose_name='DLC관리유형상세코드')),
                ('DLCM_NM', models.CharField(max_length=100, verbose_name='DLC관리명')),
                ('DLCM_EXPLN', models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='DLC관리설명')),
                ('TABLE_HANGL_NM', models.CharField(max_length=100, verbose_name='테이블한글명')),
                ('TABLE_NM', models.CharField(max_length=100, verbose_name='테이블명')),
                ('DLCM_SEQ', models.IntegerField(editable=False, verbose_name='DLC관리순번')),
                ('USE_YN', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='사용여부')),
                ('CMD_TYPE_CD', models.CharField(choices=[('AURORA_SQL', 'AURORA_SQL'), ('ATHENA_SQL', 'ATHENA_SQL'), ('DYNAMODB_QRY', 'DYNAMODB_QRY'), ('REDSHIFT_SQL', 'REDSHIFT_SQL'), ('SHELL', 'SHELL'), ('ETC', 'ETC')], default='01', max_length=30, verbose_name='명령유형코드')),
                ('CMD_CNTS', models.TextField(blank=True, default=None, max_length=14000, null=True, verbose_name='명령내용')),
                ('RGSTR_ID', models.CharField(default='DA', max_length=30, verbose_name='등록자ID')),
                ('RGST_DTTM', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('MODR_ID', models.CharField(default='DA', max_length=30, verbose_name='수정자ID')),
                ('MODI_DTTM', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
        ),
        migrations.RemoveField(
            model_name='vrfy',
            name='VRFY_TYPE_DTL_CD',
        ),
        migrations.AddField(
            model_name='vrfy',
            name='VRFY_TYPE_CD',
            field=models.CharField(choices=[('DMN', '도메인검증'), ('REF', '참조검증'), ('NT_NML', '비정규검증'), ('BIZ_RUL', '업무규칙검증')], default='BIZ_RUL', max_length=30, verbose_name='검증유형코드'),
        ),
        migrations.AlterField(
            model_name='vrfy',
            name='CMD_CNTS',
            field=models.TextField(blank=True, default=None, max_length=14000, null=True, verbose_name='명령내용'),
        ),
        migrations.AlterField(
            model_name='vrfy',
            name='CMD_TYPE_CD',
            field=models.CharField(choices=[('AURORA_SQL', 'AURORA_SQL'), ('ATHENA_SQL', 'ATHENA_SQL'), ('DYNAMODB_DLC', 'DYNAMODB_DLC'), ('REDSHIFT_SQL', 'REDSHIFT_SQL'), ('SHELL', 'SHELL'), ('ETC', 'ETC')], default='01', max_length=30, verbose_name='명령유형코드'),
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 15, 3, 31, 470196), verbose_name='마지막수행일시'),
        ),
        migrations.AlterField(
            model_name='vrfylog',
            name='CMD_CNTS',
            field=models.TextField(blank=True, default=None, max_length=14000, null=True, verbose_name='명령내용'),
        ),
    ]
