# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0009_auto_20180720_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dlcm',
            new_name='Ilm',
        ),
        migrations.RenameField(
            model_name='ilm',
            old_name='DLCM_EXPLN',
            new_name='ILM_EXPLN',
        ),
        migrations.RenameField(
            model_name='ilm',
            old_name='DLCM_NM',
            new_name='ILM_NM',
        ),
        migrations.RenameField(
            model_name='ilm',
            old_name='DLCM_NO',
            new_name='ILM_NO',
        ),
        migrations.RenameField(
            model_name='ilm',
            old_name='DLCM_SEQ',
            new_name='ILM_SEQ',
        ),
        migrations.RenameField(
            model_name='ilm',
            old_name='DLCM_TYPE_DTL_CD',
            new_name='ILM_TYPE_DTL_CD',
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 15, 9, 49, 665828), verbose_name='마지막수행일시'),
        ),
    ]
