# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0010_auto_20180720_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 15, 10, 19, 207518), verbose_name='마지막수행일시'),
        ),
    ]
