# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0013_auto_20180720_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilm',
            name='ILM_TYPE_DTL_CD',
        ),
        migrations.AddField(
            model_name='ilm',
            name='EXPCT_CNT',
            field=models.IntegerField(default=0, null=True, verbose_name='예상건수'),
        ),
        migrations.AddField(
            model_name='ilm',
            name='ILM_TYPE_CD',
            field=models.CharField(choices=[('ARC', '아카이빙'), ('DEL', '데이터삭제'), ('COPY', '복제'), ('ETC', '기타')], default='BIZ_RUL', max_length=30, verbose_name='ILM유형코드'),
        ),
        migrations.AddField(
            model_name='ilm',
            name='PRESER_PRD_VAL',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='보존기간값'),
        ),
        migrations.AlterField(
            model_name='ilm',
            name='ILM_EXPLN',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='ILM설명'),
        ),
        migrations.AlterField(
            model_name='ilm',
            name='ILM_NM',
            field=models.CharField(max_length=100, verbose_name='ILM명'),
        ),
        migrations.AlterField(
            model_name='ilm',
            name='ILM_NO',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ILM번호'),
        ),
        migrations.AlterField(
            model_name='ilm',
            name='ILM_SEQ',
            field=models.IntegerField(verbose_name='ILM순번'),
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 9, 33, 51, 302891), verbose_name='마지막수행일시'),
        ),
    ]
