# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0014_auto_20180723_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilm',
            name='CMD_TYPE_CD',
            field=models.CharField(choices=[('AURORA_SQL', 'AURORA_SQL'), ('ATHENA_SQL', 'ATHENA_SQL'), ('DYNAMODB_TTL', 'DYNAMODB_TTL'), ('REDSHIFT_SQL', 'REDSHIFT_SQL'), ('SHELL', 'SHELL'), ('ETC', 'ETC')], default='01', max_length=30, verbose_name='명령유형코드'),
        ),
        migrations.AlterField(
            model_name='vrfy',
            name='CMD_TYPE_CD',
            field=models.CharField(choices=[('AURORA_SQL', 'AURORA_SQL'), ('ATHENA_SQL', 'ATHENA_SQL'), ('DYNAMODB_QRY', 'DYNAMODB_QRY'), ('REDSHIFT_SQL', 'REDSHIFT_SQL'), ('SHELL', 'SHELL'), ('ETC', 'ETC')], default='01', max_length=30, verbose_name='명령유형코드'),
        ),
        migrations.AlterField(
            model_name='vrfy_cmd',
            name='LAST_EXE_DTTM',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 16, 10, 27, 261618), verbose_name='마지막수행일시'),
        ),
    ]
